---

resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest

resources:
- name: paving
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal/paving.git
    private_key: ((git_ssh_key))

- name: terraform
  type: terraform
  source:
    env_name: ((env_name))
    backend_type: remote
    backend_config:
      hostname: app.terraform.io
      organization:  ((app_terraform_io_org))
      token: ((app_terraform_io_token))
      workspaces:
        name: ((env_name))
    delete_on_failure: true
    vars:
      environment_name: ((env_name))
      region: ((region))
      dns_suffix: ((dns_suffix))
      hosted_zone: ((hosted_zone))
      availability_zones: ((availability_zones))
      access_key: ((aws_access_key))
      secret_key: ((aws_secret_key))
      terraform_source_iaas: ((iaas))

jobs:      
- name: paving-apply
  plan:
    - get: paving
      trigger: false
    - put: terraform
      params:
        env_name: ((env_name))
        terraform_source: paving/((iaas))
    - task: show-outputs
      config:
        platform: linux
        inputs:
          - name: terraform
        run:
          path: /bin/sh
          args:
            - -c
            - |
              echo "name: $(cat terraform/name)"
              echo "metadata: $(cat terraform/metadata)"
- name: paving-destroy
  plan:
    - get: paving
      trigger: false
    - put: terraform
      get_params:
        action: destroy
      params:
        action: destroy
        env_name: ((env_name))
        terraform_source: paving/((iaas))
